#!/bin/bash
notify-send "DUNST_COMMAND_PAUSE"
sleep .2
scrot /tmp/screenshot.png
ffmpeg -loglevel quiet -y -i /tmp/screenshot.png -vf "gblur=sigma=15" /tmp/screenshotblur.png
i3lock --nofork -f -e -i /tmp/screenshotblur.png
notify-send "DUNST_COMMAND_RESUME"
