#!/usr/bin/env bash

declare sshot=$HOME/tmp_screenshot.png

pkill compton
sleep .2
notify-send "DUNST_COMMAND_PAUSE"
scrot "$sshot"

while getopts ":bp" opt ; do
	case $opt in
		b)
			# blur - slower
			ffmpeg -loglevel quiet -y -i "$sshot" -vf "gblur=sigma=15" "$sshot"
			;;
		p)
			# pixelize - faster
			convert "$sshot" -scale 10% -scale 1000% "$sshot"
			;;
		\?)
			;;
	esac
done

i3lock --nofork -f -e -i $sshot
compton -b
rm $sshot
notify-send "DUNST_COMMAND_RESUME"
