#! /usr/bin/env bash

if [ $(pgrep -cx panel) -gt 1 ] ; then
	printf "%s\n" "The panel is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"
xtitle -sf 'T%s' > "$PANEL_FIFO" &
clock -sf 'S%a %H:%M' > "$PANEL_FIFO" &
mpc idleloop player > "$PANEL_FIFO" &
#battery -d > "$PANEL_FIFO" &
any_updates -d > "$PANEL_FIFO" &
echo "p" > "$PANEL_FIFO" &
echo "D$(date | cut -d " " -f 1,2,3)" > "$PANEL_FIFO" &


bash /home/jj/scripts/cwmpanel.d/panel_bar < "$PANEL_FIFO" | lemonbar \
	-f "-*-termsynu-medium-*-*-*-11-*-*-*-*-*-*-*" \
	-f "-wuncon-siji-medium-r-normal--10-100-75-75-c-80-iso10646-1" \
	-d \
	-p \
	-B "#00050505" \
	-F "#fff0f0f0" \
	-g x27++15 \
	-U "#F59BB0" \
	-u 2

#	-f "-artwiz-drift-medium-r-normal--10-100-75-75-n-60-iso10646-1"\

wait
